### ISSUE TITLE
[FEAT] 상품 검색에 Cache 적용

### ISSUE THREAD

**Issue by ChungHyunWoo-07** [Spring-plush-05JO/ticket-backend#19]

**Comment by loadkrnis** [comment]
https://velog.io/@komment/%EC%BA%90%EC%8B%9C%EB%A5%BC-%ED%99%9C%EC%9A%A9%ED%95%98%EC%97%AC-%EB%B6%80%ED%95%98%EB%A5%BC-%EC%A4%84%EC%9D%B4%EA%B3%A0-%EC%84%B1%EB%8A%A5%EC%9D%84-%EA%B0%9C%EC%84%A0%ED%95%98%EC%9E%90
