### ISSUE TITLE
우리들의 컨벤션 

### ISSUE THREAD

**Issue by dbrjsdn2051** [Spring-plush-05JO/ticket-backend#2]
<br>

## 에러 처리

ErrorCode 

```java
@Getter
public enum ErrorCode {

    USER_NOT_FOUND(404, "유저 정보를 찾을 수 없습니다."),  <= 추가된 에러 코드 
    ; 

    private final int status;
    private final String message;

    ErrorCode(int status, String message) {
        this.status = status;
        this.message = message;
    }
}

```

- 해당 클래스에서 Http 상태 코드와 에러 메시지에 관한 내용을 만들어 주세요 !!

에러 던지기

```java
public UserCreateRespDto addUser(UserCreateReqDto dto) {
		userRepository.findByEmail(dto.getEmail())
					.ifPresent(user -> {
				         throw new  CustomApiException(ErrorCode.EXISTS_EMAIL); <= 에러 처리!! 
				});
		dto.setPassword(passwordEncoder.encode(dto.getPassword()));
		return new UserCreateRespDto(userRepository.save(UserCreateReqDto.from(dto)).getId());
}
```

- throw new CustomApiException(ErrorCode.{Enum 클래스에서 만든 에러 명시!!})

<br><br><br>

## DTO

DTO 네이밍 규칙 

- 도메인 이름 + 행위 + {요청/응답} + Dto
- Ex. `UserCreateRepDto`
- Ex. `UserCreateRespDto`
ps. record 클래스 사용해봐도 좋아요 !! 

<br><br><br>

## 제약 사항

공통 설정 파일 

- `application.yml`, `application-dev.yml` 파일은 로컬에서 수정해도 되지만 수정된 내용을 PR 하시면 안돼요 (다른사람은 설정정보가 달라 오류가 발생할 수 있어요!!)
- 본인이 로컬에 설치한 mysql 을 사용하고 싶다면 `application-test.yml` 을 추가한 후 설정 정보를 넣은 후 `application.yml` 파일에서 `spring-profies-active:test`  로 수정후 테스트 하면 되요 !!

### 이건 어떤가요 ??

- 칸반보드를 만들어 두었습니다. 본인이 맡은 파트에 대한 이슈를 모두 작성한후 칸반보드에 TODO를 생성해보세요. 프로젝트 진행 상황을 한눈에 보기 편하답니다. (`애자일 SW 개발!!`)
- `PR `날릴때는 **2**명의 리뷰어를 지정해 **2**명의 리뷰어가 `Apporve` 했을 때 `dev` 브랜치에 `Merge`할 수 있는 정책해보는 건 어떨까요 ?

**Comment by 0han7** [comment]
너무 좋습니다.👍👍
