### ISSUE TITLE
[FEAT] 공연리스트 조회

### ISSUE THREAD

**Issue by 11ioo** [Spring-plush-05JO/ticket-backend#6]
***공연리스트 조회***

📌` GET /api/v1/performances?startdate=2024-10-25&enddate=2024-11-25&mainaddress=서울시&subaddress=종로구` 

* 공공데이터를 불러와서 공연리스트를 조회라수있게한다.

***공연리스트 조회 Request***
```json
{
  {
   "startDate":2024-10-25 ,
   "endDate": 2024-11-25,
   " mainAddress": "서울시",
   "subAddress": "종로구"
  }
}
```

***공연리스트 조회 ReseponseBody***
```json
{
  "List":
   [
    {
    "id": "1",
    "name": "캣츠",
    "genre":"뮤지컬",
    "place": "공연장",
    "startDate ": 2024-10-25 ,
    "endDate": 2024-11-25,
    " mainAddress": "서울시",
    " subAddress": "종로구"
    }
  ]
}
```
* 페이징 처리예정

**Comment by loadkrnis** [comment]
/api/v1/performances?startdate=2024-11-12&enddate=2024-11-21&mainaddress=ddd&subaddress=ddd
